spring:
  application:
      name: dobby-api-server
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true
  data:
    jpa:
      repositories:
        bootstrap-mode: deferred

logging:
  level:
    org.hibernate.type: TRACE
